apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: wait
  namespace: app-b
spec:
  args:
  - name: duration
    value: "30"
  metrics:
  - name: wait
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: busybox
                command: ["sh", "-c", "echo 'waiting {{args.duration}}s...' && sleep {{args.duration}}"]
              restartPolicy: Never
          backoffLimit: 0
