apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: app-a
  namespace: app-a
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: app-b
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: app-b
  namespace: app-b
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true
