apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-app-a
  namespace: kargo-helm
spec:
  vars:
  - name: repoURL
    value: https://github.com/zswanson/kargo-helm.git

  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - commit: ${{ commitFrom( vars.repoURL ).ID }}
        path: ./src
      - branch: stage/${{ ctx.stage }}
        create: true
        path: ./out
  - uses: git-clear
    config:
      path: ./out
  - uses: copy
    config:
      inPath: ./src/charts/guestbook
      outPath: ./out/charts/guestbook
  - uses: copy
    config:
      inPath: ./src/env-a/${{ ctx.stage }}/values.yaml
      outPath: ./out/values.yaml
  - uses: copy
    config:
      inPath: ./src/base-a/feature-flags.yaml
      outPath: ./out/feature-flags.yaml
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: "promote ${{ ctx.stage }} from ${{ commitFrom( vars.repoURL ).ID }}"
  - uses: git-push
    config:
      path: ./out

---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-app-b
  namespace: kargo-helm
spec:
  vars:
  - name: repoURL
    value: https://github.com/zswanson/kargo-helm.git

  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - commit: ${{ commitFrom( vars.repoURL ).ID }}
        path: ./src
      - branch: stage/${{ ctx.stage }}
        create: true
        path: ./out
  - uses: git-clear
    config:
      path: ./out
  - uses: copy
    config:
      inPath: ./src/charts/guestbook
      outPath: ./out/charts/guestbook
  - uses: copy
    config:
      inPath: ./src/env-b/${{ ctx.stage }}/values.yaml
      outPath: ./out/values.yaml
  - uses: copy
    config:
      inPath: ./src/base-b/feature-flags.yaml
      outPath: ./out/feature-flags.yaml
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: "promote ${{ ctx.stage }} from ${{ commitFrom( vars.repoURL ).ID }}"
  - uses: git-push
    config:
      path: ./out
