apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-app-a
  namespace: kargo-helm
spec:
  vars:
  - name: repoURL
    value: https://github.com/zswanson/kargo-helm.git
  - name: branch
    value: main

  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: ${{ vars.branch }}
        path: ./out
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - commit: ${{ commitFrom( vars.repoURL ).ID }}
        path: ./source
  - uses: copy
    config:
      inPath: ./source/base-a/feature-flags.yaml
      outPath: ./out/env-a/${{ ctx.stage }}/feature-flags.yaml
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: "updates ${{ ctx.stage }} from ${{ commitFrom( vars.repoURL ).ID }}"
  - uses: git-push
    config:
      path: ./out
  - uses: argocd-update
    config:
      apps:
      - name: kargo-helm-${{ ctx.stage }}

---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-app-b
  namespace: kargo-helm
spec:
  vars:
  - name: repoURL
    value: https://github.com/zswanson/kargo-helm.git
  - name: branch
    value: main

  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: ${{ vars.branch }}
        path: ./out
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - commit: ${{ commitFrom( vars.repoURL ).ID }}
        path: ./source
  - uses: copy
    config:
      inPath: ./source/base-b/feature-flags.yaml
      outPath: ./out/env-b/${{ ctx.stage }}/feature-flags.yaml
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: "updates ${{ ctx.stage }} from ${{ commitFrom( vars.repoURL ).ID }}"
  - uses: git-push
    config:
      path: ./out
  - uses: argocd-update
    config:
      apps:
      - name: kargo-helm-${{ ctx.stage }}
