apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: app-a-dev
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: green
    kargo.akuity.io/argocd-context: '[{"name":"kargo-helm-app-a-dev","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-app-a

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: app-a-staging
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: yellow
    kargo.akuity.io/argocd-context: '[{"name":"kargo-helm-app-a-staging","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
        - app-a-dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-app-a

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: app-a-prod-us
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
    kargo.akuity.io/argocd-context: '[{"name":"kargo-helm-app-a-prod-us","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
        - app-a-staging
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-app-a

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: app-a-prod-eu
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
    kargo.akuity.io/argocd-context: '[{"name":"kargo-helm-app-a-prod-eu","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
        - app-a-staging
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-app-a

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: app-b-dev
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: green
    kargo.akuity.io/argocd-context: '[{"name":"kargo-helm-app-b-dev","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-b
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-app-b

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: app-b-staging
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: yellow
    kargo.akuity.io/argocd-context: '[{"name":"kargo-helm-app-b-staging","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-b
    sources:
      stages:
        - app-b-dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-app-b

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: app-b-prod-us
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
    kargo.akuity.io/argocd-context: '[{"name":"kargo-helm-app-b-prod-us","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-b
    sources:
      stages:
        - app-b-staging
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-app-b
