apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: main
  namespace: app-a
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      repoURL: https://github.com/zswanson/kargo-helm.git
      includePaths:
      - base-a/feature-flags.yaml

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: main
  namespace: app-b
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      repoURL: https://github.com/zswanson/kargo-helm.git
      includePaths:
      - base-b/feature-flags.yaml
