apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: appA
  namespace: kargo-helm
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      repoURL: https://github.com/zswanson/kargo-helm.git
      includePaths:
      - baseA/feature-flags.yaml

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: appB
  namespace: kargo-helm
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      repoURL: https://github.com/zswanson/kargo-helm.git
      includePaths:
      - baseB/feature-flags.yaml
