apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-a
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: dev
      - stage: staging
      - stage: prod-us
      - stage: prod-eu
  template:
    metadata:
      name: app-a-{{stage}}
      labels:
        kargo.akuity.io/project: app-a
        kargo.akuity.io/stage: "{{stage}}"
      annotations:
        kargo.akuity.io/authorized-stage: app-a:{{stage}}
    spec:
      destination:
        namespace: app-a-{{stage}}
        server: https://kubernetes.default.svc
      project: kargo-helm
      source:
        path: app-a/charts/guestbook
        repoURL: https://github.com/zswanson/kargo-helm.git
        targetRevision: stage/{{stage}}
        helm:
          valueFiles:
          - /app-a/values.yaml
          - /app-a/feature-flags.yaml
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-b
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: dev
      - stage: staging
      - stage: prod-us
  template:
    metadata:
      name: app-b-{{stage}}
      labels:
        kargo.akuity.io/project: app-b
        kargo.akuity.io/stage: "{{stage}}"
      annotations:
        kargo.akuity.io/authorized-stage: app-b:{{stage}}
    spec:
      destination:
        namespace: app-b-{{stage}}
        server: https://kubernetes.default.svc
      project: kargo-helm
      source:
        path: app-b/charts/guestbook
        repoURL: https://github.com/zswanson/kargo-helm.git
        targetRevision: stage/{{stage}}
        helm:
          valueFiles:
          - /app-b/values.yaml
          - /app-b/feature-flags.yaml
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
